practice/baseapp/urls.py
from django.urls import path
from . import views

app_name = "baseapp"

urlpatterns = [
    path('', views.langpage, name="landpage"),
    path('login/', views.login, name="login"),
    path('gmail_login/', views.gmail_login, name="gmail_login"),
    path('gmail_ca/', views.gmail_ca, name="gmail_ca"),
    path('facebook_login/', views.facebook_login, name="facebook_login"),
    path('facebook_ca/', views.facebook_ca, name="facebook_ca"),
    path('create_account/', views.create_account, name="create_account"),
    path('logout/', views.logout, name="logout"),
    path('homepage/', views.homepage, name="homepage"),
    path('profile/', views.profile, name="profile"),
]

practice/mongodb/urls.py
from django.urls import path
from . import views

app_name = "mongodb"

urlpatterns = [
    path('', views.index_page, name="index"),
]

practice/practice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("mongodb/", include("mongodb.urls")),
    path("", include("baseapp.urls")),
]

practice/baseapp/models.py
from django.db import models

# Create your models here.

practice/mongodb/models.py
from django.db import models

# Create your models here.

practice/supabasedb/models.py
from django.db import models

# Create your models here.

practice/baseapp/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from . import customlogin
from supabasedb import supabase

# Create your views here.
def langpage(request) :
    return render (request, "baseapp/landpage.html")

def gmail_login(request) :
    gm = customlogin.Gmail_login()
    info = gm.authenticate_with_google()        
    info = {
        "email" : info["email"],
        "name" : "name"
    }
    request.session["info"] = info
    return redirect('baseapp:login')

def gmail_ca(request) :
    gm = customlogin.Gmail_login()
    info = gm.authenticate_with_google()
    info = {
        "email" : info["email"],
        "name" : info["name"],
    }
    request.session["info"] = info
    return redirect('baseapp:create_account')

def facebook_login(request) :
    fb = customlogin.Facebook_login()
    info = fb.work()

    request.session["info"] = info
    return redirect('baseapp:login')

def facebook_ca(request) :
    fb = customlogin.Facebook_login()
    info = fb.work()   

    request.session["info"] = info
    return redirect('baseapp:create_account')

@csrf_exempt
def login(request) :
    if request.COOKIES.get("remember_me") == "true":
        return redirect("baseapp:homepage")    

    if request.method == "POST" :
        email = request.POST.get("email")
        password = request.POST.get("password")
        remember_me = request.POST.get("remember_me")
        value = request.POST.get("action")

        supa = supabase.Supabase()
        response = supa.login_account(email, password)

        if response == False :
            messages.error(request, "Login unsuccessful.")
            return redirect("baseapp:login")
       
        button = request.POST.get("submit_btn")
        if button == "submit" :            
            response = redirect("baseapp:homepage")
            if remember_me == "on" :
                response.set_cookie("remember_me", "true", max_age=31536000, samesite='Lax', secure=False)
            return response
    
    info = request.session.get("info")
    
    return render(request, "baseapp/login.html", info)

def create_account(request) :
    info = request.session.get("info")

    if request.method == "POST" :
        name = request.POST.get("name")
        email = request.POST.get("email")
        password = request.POST.get("password")

        supa = supabase.Supabase()
        response = supa.create_account(name, email, password)        
        
    return render(request, "baseapp/createAcc.html", info)

def logout(request) :
    if "info" in request.session :
        del request.session["info"]
    response = redirect("baseapp:login")
    response.delete_cookie("remember_me")
    

    return response

def homepage(request) :
    # if request.COOKIES.get("remember_me") == "true":
    return render(request, "baseapp/homepage.html")
    
    # return redirect("baseapp:login")

def profile(request) :
    return render(request, "baseapp/profile.html")

practice/mongodb/views.py
from django.shortcuts import render

# Create your views here.

def index_page(request) :
    return render(request, "mongodb\index.html")

practice/supabasedb/views.py
from django.shortcuts import render

# Create your views here.

practice/baseapp/templates/baseapp/createAcc.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/login.css" %}">
    <title>Create Account</title>
</head>
<body>
    <form method="post" action="{% url "baseapp:login" %}">
        {% csrf_token %}
        <h1>Create Account</h1>
        <input type="text" name="name" value="{{name}}" placeholder="Full Name">
        <input type="text" name="email" value="{{email}}" placeholder="Email">
        <input type="password" name="password" value="" placeholder="Password">
        <button type="button" onclick="window.location.href={% url "baseapp:gmail_ca" %}">Gmail</button>
        <button type="button" onclick="window.location.href={% url "baseapp:facebook_ca" %}">Facebook</button>
        <button type="submit">Create Account</button>
    </form>
</body>
</html>

practice/baseapp/templates/baseapp/homepage.html
{% extends "baseapp/mainapp.html" %}
{% load static %}
{% block content %}
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
<h1>Home Page</h1>
{% endblock content %}

practice/baseapp/templates/baseapp/landpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landpage</title>
</head>
<body>
    {% comment %} <a href="{% url "login" %}">Button</a> {% endcomment %}
    <button onclick="window.location.href={% url "baseapp:login" %}">Login</button>
    <button onclick="window.location.href={% url "baseapp:logout" %}">Logout</button>
    <button onclick="window.location.href={% url "baseapp:create_account" %}">Create Account</button>
</body>
</html>

practice/baseapp/templates/baseapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/login.css" %}">
    <title>Login</title>
</head>
<body>
    <form method="post" action="{% url "baseapp:login" %}">
        {% csrf_token %}
        <h1>Login</h1>
        <input type="text" name="email" placeholder="Email" value="{{email}}">
        <input type="text" name="password" placeholder="Password">
        <label>
            <input type="checkbox" name="remember_me"> Remember Me
        </label>        
        <button type="button" onclick="window.location.href={% url "baseapp:gmail_login" %}">Gmail</button>
        <button type="button" onclick="window.location.href={% url "baseapp:facebook_login" %}">Facebook</button>
        <button type="submit" name="submit_btn" value="submit">Login</button>
    </form>
</body>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    {% if messages %}
        {% for message in messages %}
            alert("{{message}}") ;
        {% endfor %}
    {% endif %}
</script>
</html>

practice/baseapp/templates/baseapp/mainapp.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% comment %} font awesome css link {% endcomment %}
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
      integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="{% static "css/style.css" %}?v={{ timestamp }}">
    <title>Home Page</title>
</head>
<body>
    <header>
        <div class="logo"></div>
        <div class="options">
            <i class="fa-solid fa-user" onclick="window.location.href={% url "baseapp:profile" %}"></i>
            <i class="fa-solid fa-gear"></i>                
            <i class="fa-solid fa-right-from-bracket" onclick="window.location.href={% url "baseapp:logout" %}"></i>
        </div>
    </header>
    <div class="main-body">
    <nav>
        <ul class="option">
            <li>Home</li>
            <li onclick="expandFunction(0)">
                Database
                <i class="fa-solid fa-angle-down"></i>
            </li>
                <ul class="suboption">
                    <li>Supabase</li>
                    <li>MySQL</li>
                    <li>SQL Lite</li>
                    <li>MongoDB</li>
                    <li>MariaDB</li>
                </ul>
            <li onclick="expandFunction(1)">
                Payment
                <i class="fa-solid fa-angle-down"></i>
            </li>
                <ul class="suboption">
                    <li>Strip</li>
                    <li>Bkash</li>
                    <li>Nagad</li>
                    <li>Visa/Master</li>
                </ul>
            <li onclick="expandFunction(2)">
                MS
                <i class="fa-solid fa-angle-down drop"></i>
            </li>
                <ul class="suboption">
                    <li>MS Word</li>
                    <li>MS Excel</li>
                </ul>           
            <li>Data Visualization</li>
            <li>About Me</li>
            <li onclick="window.location.href={% url "baseapp:logout" %}">Logout</li>
        </ul>
    </nav>
    <main>
        <div class="container">
            {% block content %}{% endblock content %}
        </div>    
    </main>
    </div>
</body>
<script>
    window.onload = function() {
        document.title = "{% block title_name %}Home Page{% endblock title_name %}" ;
    }
</script>
<script src="{% static "script/script.js" %}"></script>
</html>

practice/baseapp/templates/baseapp/profile.html
{% extends "baseapp/mainapp.html" %}
{% block content %}
<h1 class="page-title">Profile</h1>
<h4>Full Name</h4>
<p>name</p>
<h4>Email</h4>
<p>email</p>
<h4>Password</h4>
<p>password</p>
<button class="cbtn">Change Information</button>
{% endblock content %}

{% block title_name %}Profile{% endblock title_name %}

practice/mongodb/templates/mongodb/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MongoDB</title>
</head>
<body>
    <h1>MongoDB</h1>
</body>
</html>